language: node_js
node_js:
  - '0.10'
before_install:
  - gem install sass -v 3.4.5
  - gem install compass
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
script:
  - grunt
notifications:
  email:
    recipients:
      - guym@gigaspaces.com
    on_success: never
    on_failure: always